// <auto-generated />
namespace AulpagMailing.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class tb_envoi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tb_envoi));
        
        string IMigrationMetadata.Id
        {
            get { return "202206101006179_tb_envoi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
